# **Modular Arithmetic**

Modular arithmetic is a system of arithmetic for integers, where numbers "wrap around" upon reaching a certain value, called the modulus. This means that after reaching the modulus, numbers start back at zero.

The basic operation in modular arithmetic is to find the remainder when one integer is divided by another (the modulus).

For a given modulus $m$, any integer $a$ can be expressed in modular arithmetic as:

$$
a \mod m
$$

This represents the remainder when $a$ is divided by $m$.

For example:
- $7 \mod 5 = 2$ because $7$ divided by $5$ gives a quotient of $1$ and a remainder of $2$.
- $12 \mod 4 = 0$ because $12$ divided by $4$ gives a quotient of $3$ and a remainder of $0$.

In general:

$$
a \equiv b \mod m
$$

means that $a$ and $b$ have the same remainder when divided by $m$.

## Functions

In [1]:
import sympy as sp
from sympy import *
from math import gcd
import random

In [13]:
def modular_arithmetic(number, modulus):
    result = number % modulus
    print(f"{number} ≡ {result} (mod {modulus})")
    return

## Examples

### Finding the Remainder of $17$ mod $5$

In [9]:
number = 17
modulus = 5
modular_arithmetic(number, modulus)

17 ≡ 2 (mod 5)


```{admonition} Explanation
:class: tip

To find the remainder when $17$ is divided by $5$, follow these steps:

1. **Divide $17$ by $5$**: Compute the quotient and remainder.

$$
17 \div 5 = 3 \text{ remainder } 2
$$

2. **Express the division**:

$$
17 = 5 \times 3 + 2
$$

3. **The remainder is the result of the modulo operation**:

$$
17 \mod 5 = 2
$$

Therefore:

$$
17 \equiv 2 \mod 5
$$

```

### Finding the Remainder of $170$ mod $16$

In [11]:
number = 170
modulus = 16
modular_arithmetic(number, modulus)

170 ≡ 10 (mod 16)


```{admonition} Explanation
:class: tip

To find the remainder when $170$ is divided by $16$, follow these steps:

1. **Divide $170$ by $16$**: Compute the quotient and remainder.

$$
170 \div 16 = 10 \text{ remainder } 10
$$

2. **Express the division**:

$$
170 = 16 \times 10 + 10
$$

3. **The remainder is the result of the modulo operation**:

$$
170 \mod 16 = 10
$$

Therefore:

$$
170 \equiv 10 \mod 16
$$

```

### Finding the Remainder of $338$ mod $12$

In [10]:
number = 338
modulus = 12
modular_arithmetic(number, modulus)

338 ≡ 2 (mod 12)


```{admonition} Explanation
:class: tip

To find the remainder when 338 is divided by $12$, follow these steps:

1. **Divide $338$ by $12$**: Compute the quotient and remainder.

$$
338 \div 12 = 28 \text{ remainder } 2
$$

2. **Express the division**:

$$
338 = 12 \times 28 + 2
$$

3. **The remainder is the result of the modulo operation**:

$$
338 \mod 12 = 2
$$

Therefore:

$$
338 \equiv 2 \mod 12
$$

```

### Finding the Remainder of $90$ mod $30$

In [12]:
number = 90
modulus = 30
modular_arithmetic(number, modulus)

90 ≡ 0 (mod 30)


```{admonition} Explanation
:class: tip

To find the remainder when $90$ is divided by $30$, follow these steps:

1. **Divide $90$ by $30$**: Compute the quotient and remainder.

$$
90 \div 30 = 3 \text{ remainder } 0
$$

2. **Express the division**:

$$
90 = 30 \times 3 + 0
$$

3. **The remainder is the result of the modulo operation**:

$$
90 \mod 30 = 0
$$

Therefore:

$$
90 \equiv 0 \mod 30
$$

```

# **Modular Addition**

Modular addition involves adding two numbers and then taking the remainder when the result is divided by the modulus.

The formula for modular addition of two numbers $a$ and $b$ with modulus $m$ is:

$$
(a + b) \mod m
$$

Steps:
1. Add the numbers $a$ and $b$.
2. Take the result and apply the modulus $m$ to find the remainder.

# **Modular Subtraction**

Modular subtraction involves subtracting one number from another and then taking the remainder when the result is divided by the modulus.

The formula for modular subtraction of two numbers $a$ and $b$ with modulus $m$ is:

$$
(a - b) \mod m
$$

Steps:
1. Subtract the number $b$ from $a$.
2. If the result is negative, add the modulus $m$ until the result is non-negative.
3. Apply the modulus $m$ to find the remainder.

# **Modular Multiplication**

Modular multiplication involves multiplying two numbers and then taking the remainder when the result is divided by the modulus.

The formula for modular multiplication of two numbers $a$ and $b$ with modulus $m$ is:

$$
(a \times b) \mod m
$$

Steps:
1. Multiply the numbers $a$ and $b$.
2. Apply the modulus $m$ to find the remainder.


# **Modular Inverse**

The modular inverse of a number $a$ modulo $m$ is a number $x$ such that:

$$
a \times x \equiv 1 \mod m
$$

The modular inverse exists if and only if $a$ and $m$ are coprime (i.e., $\text{gcd}(a, m) = 1$).

To find the modular inverse of $a$ modulo $m$, you can use the Extended Euclidean Algorithm.


# **Modular Exponentiation**

Modular exponentiation involves raising a number to an exponent and then taking the remainder when the result is divided by the modulus.

The formula for modular exponentiation of a number $a$ raised to an exponent $b$ with modulus $m$ is:

$$
a^b \mod m
$$

Steps:
1. Compute the power $a^b$.
2. Apply the modulus $m$ to find the remainder.