# **Modular Addition**

Modular addition involves adding two numbers and then taking the remainder when the result is divided by the modulus.

The formula for modular addition of two numbers $a$ and $b$ with modulus $m$ is:

$$
(a + b) \mod m
$$

Steps:
1. Add the numbers $a$ and $b$.
2. Take the result and apply the modulus $m$ to find the remainder.

## Functions

In [1]:
import sympy as sp
from sympy import *
from math import gcd
import random

In [2]:
def modular_addition(a, b, modulus):
    result = (a + b) % modulus
    print(f"{a} + {b} ≡ {result} (mod {modulus})")
    return result

## Examples


### Finding $(10 + 17)~mod~7$

In [3]:
a = 10
b = 17
modulus = 7

result = modular_addition(a, b, modulus)

10 + 17 ≡ 6 (mod 7)


```{admonition} Explanation
:class: tip

To find the result of \( 10 + 17 \) modulo \( 7 \), follow these steps:

1. **Perform the addition**:

$$
10 + 17 = 27
$$

2. **Compute the remainder when divided by the modulus**:

$$
27 \div 7 = 3 \text{ remainder } 6
$$

3. **Express the division**:

$$
27 = 7 \times 3 + 6
$$

4. **The remainder is the result of the modulo operation**:

$$
27 \mod 7 = 6
$$

Therefore:

$$
10 + 17 \equiv 6 \mod 7
$$
```


### Finding $(203 + 17)~mod~10$

In [5]:
a = 203
b = 17
modulus = 10

result = modular_addition(a, b, modulus)

203 + 17 ≡ 0 (mod 10)


```{admonition} Explanation
:class: tip, dropdown

To find the result of \( 203 + 17 \) modulo \( 10 \), follow these steps:

1. **Perform the addition**:

$$
203 + 17 = 220
$$

2. **Compute the remainder when divided by the modulus**:

$$
220 \div 10 = 22 \text{ remainder } 0
$$

3. **Express the division**:

$$
220 = 10 \times 22 + 0
$$

4. **The remainder is the result of the modulo operation**:

$$
220 \mod 10 = 0
$$

Therefore:

$$
203 + 17 \equiv 0 \mod 10
$$

```

### Finding $(-43 + 128)~mod~26$

In [7]:
a = -43
b = 128
modulus = 26

result = modular_addition(a, b, modulus)

-43 + 128 ≡ 7 (mod 26)


```{admonition} Explanation
:class: tip, dropdown

To find the result of \( -43 + 128 \) modulo \( 26 \), follow these steps:

1. **Perform the addition**:

$$
-43 + 128 = 85
$$

2. **Compute the remainder when divided by the modulus**:

$$
85 \div 26 = 3 \text{ remainder } 7
$$

3. **Express the division**:

$$
85 = 26 \times 3 + 7
$$

4. **The remainder is the result of the modulo operation**:

$$
85 \mod 26 = 7
$$

Therefore:

$$
-43 + 128 \equiv 7 \mod 26
$$
```

### Finding $(3028 + 220934)~mod~85$

In [8]:
a = 3028
b = 220934
modulus = 85

result = modular_addition(a, b, modulus)

3028 + 220934 ≡ 72 (mod 85)


```{admonition} Explanation
:class: tip, dropdown

To find the result of \( 3028 + 220934 \) modulo \( 85 \), follow these steps:

1. **Perform the addition**:

$$
3028 + 220934 = 223962
$$

2. **Compute the remainder when divided by the modulus**:

$$
223962 \div 85 = 2634 \text{ remainder } 12
$$

3. **Express the division**:

$$
223962 = 85 \times 2634 + 12
$$

4. **The remainder is the result of the modulo operation**:

$$
223962 \mod 85 = 12
$$

Therefore:

$$
3028 + 220934 \equiv 12 \mod 85
$$

```