# **Modular Subtraction**

Modular subtraction involves subtracting one number from another and then taking the remainder when the result is divided by the modulus.

The formula for modular subtraction of two numbers $a$ and $b$ with modulus $m$ is:

$$
(a - b) \mod m
$$

Steps:
1. Subtract the number $b$ from $a$.
2. If the result is negative, add the modulus $m$ until the result is non-negative.
3. Apply the modulus $m$ to find the remainder.

## Functions

In [1]:
import sympy as sp
from sympy import *
from math import gcd
import random

In [4]:
def modular_subtraction(a, b, modulus):
    result = (a - b) % modulus
    print(f"{a} - {b} ≡ {result} (mod {modulus})")
    return result

## Examples

### Finding $(10 - 17)~mod~7$

In [5]:
a = 10
b = 17
modulus = 7

result = modular_subtraction(a, b, modulus)

10 - 17 ≡ 0 (mod 7)


```{admonition} Explanation
:class: tip

To find the result of \( 10 - 17 \) modulo \( 7 \), follow these steps:

1. **Perform the subtraction**:

$$
10 - 17 = -7
$$

2. **Adjust to ensure the result is within the range 0 to modulus-1**:

Since we have a negative result, we adjust it by adding the modulus until it becomes non-negative:

$$
-7 + 7 = 0
$$

3. **The adjusted result is the result of the modulo operation**:

$$
10 - 17 \equiv 0 \mod 7
$$

```

### Finding $(217 - 240)~mod~19$

In [14]:
a = 217
b = 240
modulus = 19

result = modular_subtraction(a, b, modulus)

217 - 240 ≡ 15 (mod 19)


```{admonition} Explanation
:class: tip, dropdown

To find the result of \( 217 - 240 \) modulo \( 19 \), follow these steps:

1. **Perform the subtraction**:

$$
217 - 240 = -23
$$

2. **Adjust to ensure the result is within the range 0 to modulus-1**:

Since we have a negative result, we adjust it by adding the modulus until it becomes non-negative:

$$
-23 + 19 = -4
$$

3. **Find the remainder when divided by the modulus**:

Now, calculate the remainder when \( -4 \) is divided by \( 19 \):

$$
-4 \mod 19 = 15
$$

Therefore:

$$
217 - 240 \equiv 15 \mod 19
$$

```

### Finding $(2293 - 334)~mod~38$

In [12]:
a = 2293
b = 334
modulus = 38

result = modular_subtraction(a, b, modulus)

2293 - 334 ≡ 21 (mod 38)


```{admonition} Explanation
:class: tip, dropdown

To find the result of \( 2293 - 334 \) modulo \( 38 \), follow these steps:

1. **Perform the subtraction**:

$$
2293 - 334 = 1959
$$

2. **Find the remainder when divided by the modulus**:

Now, calculate the remainder when \( 1959 \) is divided by \( 38 \):

$$
1959 \div 38 = 51 \text{ remainder } 21
$$

3. **Express the division**:

$$
1959 = 38 \times 51 + 21
$$

4. **The remainder is the result of the modulo operation**:

$$
1959 \mod 38 = 21
$$

Therefore:

$$
2293 - 334 \equiv 21 \mod 38
$$

```